### ISSUE TITLE
Feature Request: Close to Tray

### ISSUE THREAD

**Issue by mfreeman-xtivia** [mike-ward/tweetz#104]
While Tweetz already supports the use of a tray icon, it would be nice if you could add a settings option something along the lines of "Close to Tray". When i am running it in the tray I often times forget and click the X for close instead of the minimize button.

**Comment by mike-ward** [comment]
Sounds like what you really want is an option to hide the close button in the title bar. Does that sound right?

**Comment by mfreeman-xtivia** [comment]
Yes that would accomplish the same goal.

**Comment by mike-ward** [comment]
v2022.2
