### ISSUE TITLE
Pictures are often truncated, showing only the top.

### ISSUE THREAD

**Issue by gungfujoe** [mike-ward/tweetz#118]
I see this fairly often. Tweets that show images that have very large original versions will show only the top portion.  [Here's an example that I captured](https://i.imgur.com/LUbNXBk.png), where you can see my entire screen (with the Tweetz Issues page maximized and Tweetz displayed on top of it), after I've clicked on the [Snopes tweet](https://twitter.com/snopes/status/1532123184526512134) that's visible in the bottom right.  The tweet (and the Snopes article) show much smaller versions of the picture, but Tweetz digs into the HTML code to pull the largest version that's available, and then truncates it.

I'm using Tweetz v2022.2 on Windows 10 Pro x64.

**Comment by gungfujoe** [comment]
Thanks for the quick response.  Sorry WPF's developer community is so unfriendly. Their responses suggest there might be some way to do what you want, but that they have no interest in helping you find it. That's really unfortunate.

**Comment by mike-ward** [comment]
v2022.3
