### ISSUE TITLE
New Settings: Alway on top & Close to tray

### ISSUE THREAD

**Issue by zennessless** [mike-ward/tweetz#12]
Hi Mike, it would be great to see **Alway on top** feature & **Close to tray** options in future releases.

Of course **Close to tray** will need to implement try icon _Right-click -> Exit functions_. The same can be applied to **Alway on top** option.

Thank you very much!!

**Comment by mike-ward** [comment]
**Always on Top** I get.

**Minimize to Tray**? So you want an **Always on Top** program you can minimize to the system tray? And then a popup menu on that tray icon to exit? Why not just close the program? 

You do know there's a setting in task bar to only show icons? https://helpdeskgeek.com/how-to/remove-text-icons-windows-taskbar/

Also, you can shrink the size of the task bar icons in the settings. They're almost as small as the tray icons at that point.

**Comment by zennessless** [comment]
Thank you very much Mike!
By "Closing to tray" I mean sometimes we want the Desktop to be clear to focus on other things but the Tweetz to be still on tray to open it on click. That's the point of that little function.

Anyway, big thanks!

**Comment by mike-ward** [comment]
I can see adding a standard minimize button to the toolbar. If **Show in Tray** is checked it will minimize to tray. The exit from system tray is over kill. Just restore the window and exit.

**Comment by zennessless** [comment]
This is great Mike! Thanks!

When there apprx. will be installer/new release?

**Comment by mike-ward** [comment]
v2.3.0 released
