### ISSUE TITLE
Visual Indicator of New Messages

### ISSUE THREAD

**Issue by mfreeman-xtivia** [mike-ward/tweetz#125]
As a feature request, it would be nice if there was some kind of visual indicator when new messages arrive in my timeline. I am thinking of cases where Tweetz is minimized.

Examples would be a slightly different icon when new messages are available, or a tray indicator, etc.

**Comment by mike-ward** [comment]
Minimize? Why would you not want to see Tweetz in all it's glory all the time? :smile: 

The only visual indicator at the moment is a green dot on the home icon when the time-line is not scrolled to the top and new tweets arrive. This is to keep the timeline from jumping around when new tweets arrive and you're reviewing older tweets.

I use to have a chirp sound when new tweets arrived in a much earlier version of Tweetz. I removed it when I rewrote the program in WPF. No one ever asked for it back.

The issue with the new tweet indicator is when do you clear it? Having to click on the program to remove it is the only way I can think of. Sounds like it might be an annoyance. 

I could see maybe changing the tray icon when its minimized.

What do others think?

**Comment by mfreeman-xtivia** [comment]
The tray icon changing could be a nice solution.

So my workflow typically is to run with Tweetz minimized and then periodically pop it open to see any new tweets. I could vote for restoring the app from the minimized state as an action for clearing the 'new messages' state

**Comment by mfreeman-xtivia** [comment]
Mike could you possibly suggest where in the code someone would need to hook things or make changes to react to new message arrival?

**Comment by mike-ward** [comment]
If you only want the indicator when the app is minimized I think it's possible to do. I'm on the road right now until October. I'll have a look when I get back. I need to upgrade the app for.net 7.0 anyways.

**Comment by mfreeman-xtivia** [comment]
"Only when minimized" would work perfectly for my situation

**Comment by mike-ward** [comment]
v2022.3

**Comment by mfreeman-xtivia** [comment]
Mike
Thanks very much for the update. I am seeing a number of false positives, unfortunately (i.e. the green icon appears but there are no new tweets when i unminimize the app...

**Comment by mike-ward** [comment]
Been solid here. Can't see how it could trigger a false positive. The collection that tracks tweets has to actually change to trigger the notify. Maybe you can spot something it the code?

**Comment by mfreeman-xtivia** [comment]
I think I know what's happening...

I had "Hide Retweets" set to true. The indicator still seems to be showing to indicate new tweets even if all of those new tweets were retweets. So it gives a sense of false positives...

Is there some way to account for the "hide retweets" being true when determining whether or not to show the "new tweets" indicator?

**Comment by mike-ward** [comment]
I believe I can fix that issue. Thanks for sleuthing it out.

**Comment by mike-ward** [comment]
ignoring instead of hiding retweets.

**Comment by mike-ward** [comment]
Here's a build with a possible fix. Let me know how it goes.

https://github.com/mike-ward/tweetz/suites/9647778778/artifacts/461358902

**Comment by mfreeman-xtivia** [comment]
From what I have seen so far, this seems to be working. Thanks!!

**Comment by mike-ward** [comment]
v2022.5
