### ISSUE TITLE
Sound on new tweet

### ISSUE THREAD

**Issue by sarcinelli86** [mike-ward/tweetz#135]
I miss the chirping sound of the original app. Please bring it back or at least the option to choose the notification sound, because Windows Asterisk sound is quite irritating.

Anyway, thanks for the continued support I love this app!

**Comment by mike-ward** [comment]
You can use any sound you like. Simply edit the configuration file and supply a path to the .wav file.  Make sure to use "\\" for the path separators or the file config file won't load.

**Comment by mike-ward** [comment]
https://drive.google.com/file/d/1WEKytq2OXZMXFayuqcTe1vSsgQr69yeP/view?usp=share_link

A shorter version.

**Comment by sarcinelli86** [comment]
That's nice, thanks!

**Comment by mike-ward** [comment]
After using it for a few days, the shortened, "cricket chirp" is much nicer IMO. I'll incorporate it as the default in the next release.
