### ISSUE TITLE
API "challenges"?

### ISSUE THREAD

**Issue by irishfolk** [mike-ward/tweetz#139]
Hi there, is anyone else experiencing API hiccups lately?  

![grafik](https://user-images.githubusercontent.com/87227774/213918683-3abbd3ac-e221-40f0-852e-fe9575f9effe.png)

At the moment i am fearing that - like some other tools - tweetz might have lost API access? I tested it with v2022.5 some minutes ago

**Comment by Supernoodles1990** [comment]
turned my pc on today and the whole app was blank except settings so i went into there and logged out thinking that maybe i just needed to re-auth but getting that exact same message even fully uninstalled and reinstalled i guess we need an update

**Comment by ronzie** [comment]
My pc runs 24/7. The newest Tweet in the Tweetz app is from 11:20PM Jan 21 2023 eastern time. Twitter website seems to be updating as usual.

**Comment by irishfolk** [comment]
Interesting, thank you for your prompt additional feedback! 

Maybe geolocation is also a component here? I am opening tweetz from europe. (just for info)

**Comment by Xerxes13** [comment]
Twitter banned 3rd party apps & cut off the API, so I guess no more Tweetz ?

https://www.techdirt.com/2023/01/20/twitter-makes-it-official-no-more-3rd-party-clients-allowed/

**Comment by gungfujoe** [comment]
As noted, the API issues began about 5 days ago. But it was targeted to specific apps. Apparently they decided to ban Tweetz this morning. So far, they've offered no explanation for the targeted shutdowns, but I think it's pretty obvious that they only want people using Twitter in the way they present it.

Unless Twitter changes back to allowing third-party apps (which is certainly possible, given how erratic Musk's operation of the site has been), I'd argue this makes issue #134 even more important! 😉

**Comment by mike-ward** [comment]
After 13 years, the end has come. Twitter has disabled all third-party applications including my inconsequential little application. 😥 It was fun while it lasted. Thanks to everyone who supported me over the years.
