### ISSUE TITLE
Unable to obtain PIN

### ISSUE THREAD

**Issue by swampyankeeri** [mike-ward/tweetz#140]
This morning, 22 Jan 2023, I logged on to my work desktop computer (Dell OptiPlex 5050) running Windows 10 Pro, only to discover that Tweetz was no longer operational. Recognizing that Musk rolled out a major Twitter revision this week, I assumed that Tweetz needed to be updated.
I tried several methods to install Tweetz 2.0.0; however, when I initialize, I am instructed to click the "Get PIN" button. I click the button but immediately receive a Windows error box that just says "Unauthorized". Screen grab attached. I cannot get past this error box.
FYI - I have been using and updating Tweetz for years, on this computer and network, without issue.
Thanks.
![Tweetz](https://user-images.githubusercontent.com/123308534/213919918-519278ef-19fa-47e5-a8a3-3f11141537fc.jpg)

**Comment by irishfolk** [comment]
also see #139

**Comment by mike-ward** [comment]
After 13 years, the end has come. Twitter has disabled all third party applications including my inconsequential little application. 😥 It was fun while it lasted. Thanks to everyone who supported me over the years.
