### ISSUE TITLE
No access to settings dialog without "authorized PIN"

### ISSUE THREAD

**Issue by irishfolk** [mike-ward/tweetz#141]
Hi there,

please enable access to settings dialog (wrench icon in Header Menu) when not having an authorized Token.

After having de-authed my formerly used PIN i was not able to navigate to any tweetz related URL (because those are displayed on the settings dialog)

Background: While trying to fix the behaviour described in #139 i disabled my authorized PIN and restarted tweetz. Now i only can try to "Get PIN" but i cannot look into the settings dialog anymore. (No MenuBar on top with wrench icon)

Maybe it would be enough to include the HeaderBar in the used Dialog?

cheers

**Comment by mike-ward** [comment]
After 13 years, the end has come. Twitter has disabled all third party applications including my inconsequential little application. 😥 It was fun while it lasted. Thanks to everyone who supported me over the years.

**Comment by irishfolk** [comment]
first of all: i totally understand every possible decision. (e.g. the reasons for your answer above)

but i cannot ``not`` ask the following: 
are you maybe a little relieved that "something happened" that made maintainig this tool redundant? 

(because it appears to me, that i am more attached to it than you seem to be. if i am assuming correctly, as i said, i would understand it, tho)

thank you for making this fine tool available to us and thank you for having maintained it as long as you did! 👍 

//edit: i also could be getting it totally wrong! i was just wondering, because it felt suspiciously "light-hearted" to me 😇

**Comment by mike-ward** [comment]
Not relieved at all. In fact, I had just added colored emoji support a few weeks ago (not published however). Also working on a cross-platform version called Loon. I use tweetz ever day and will miss it. It was the only sane way for me to use twitter.

I've moved on from Twitter to Post.News. It's a little raw at the moment but much more civil than twitter. If and when they publish an API, I'll take my Loon app and port it to that platform.

**Comment by dhamann** [comment]
thank you for your prompt and detailed reply, it debugs my own thought process quite well! :) 

I was always fond of the simplicity that tweetz offered ... Are you maybe inclined to open a pathway to have tweetz-like simplicity in one of your tools for a bouquet of services? (think: tweetzlike sidebar-simplicity with adapter/plugin for $serviceXY (mastodon / Post.News / ... ) ?

Even if Twitter might reverse their stand again, why should they not re-reverse it again? 🤷

**Comment by irishfolk** [comment]
thank you for your prompt and detailed reply, it debugs my own thought process quite well! :) 

I was always fond of the simplicity that tweetz offered ... Are you maybe inclined to open a pathway to have tweetz-like simplicity in one of your tools for a bouquet of services? (think: tweetzlike sidebar-simplicity with adapter/plugin for $serviceXY (mastodon / Post.News / ... ) ?

Even if Twitter might reverse their stand again, why should they not re-reverse it again? 🤷 

(sry, deleted and accountswitch for continuity 😊 )
