### ISSUE TITLE
B&W option

### ISSUE THREAD

**Issue by spektaakkeli** [mike-ward/tweetz#32]
Hi, love the product!
I have a totally black & white desktop (except Tweetz) and would love
to have an option to see tweet feed in b&w (gray scale).

**Comment by mike-ward** [comment]
Interesting idea. Black on white or white on black? Any screenshots you care to share?

**Comment by spektaakkeli** [comment]
![tweetz01](https://user-images.githubusercontent.com/7249018/88187431-2ee53280-cc3f-11ea-87f8-20787eb0a564.jpg)
![tweetz02](https://user-images.githubusercontent.com/7249018/88187451-360c4080-cc3f-11ea-900c-49c04c841c04.jpg)

Easiest to explain this way I guess.

**Comment by mike-ward** [comment]
Thinking I might just run the current color themes through a color converter to grayscale them. Then add a checkbox to the themes to grayscale the theme.

Notes to myself: GRAY = 0.2989 * RED + 0.5870 * GREEN + 0.1140 * BLUE

**Comment by spektaakkeli** [comment]
Sounds like you might be able to make my digital life perfect ;)

**Comment by mike-ward** [comment]
Not an official build but should be stable. Have a look and send feedback.

https://github.com/mike-ward/tweetz/suites/952744662/artifacts/11900734

**Comment by spektaakkeli** [comment]
Works perfectly! Gonna smile the whole day now. Thanks!

**Comment by mike-ward** [comment]
I didn't change profiles and the image viewer figuring even in grayscale users might want to see original formats. Thoughts?

**Comment by spektaakkeli** [comment]
This is perfect now.
