### ISSUE TITLE
MBAM claims tweetz.core.exe periodically attempting to connect to Malicious Website

### ISSUE THREAD

**Issue by ronzie** [mike-ward/tweetz#35]
MBAM claims tweetz.core.exe is periodically attempting to connect to "Malicious Website" rb.gy, ip address 76.223.86.4 port 443. I don't know what their criteria are for determining what sites are malicious. The operation of the program does not seem to be affected by blocking this connection.

I am using Tweetz v 2.6.1 because I don't like the line spacing of the newer versions.

**Comment by mike-ward** [comment]
The program does log some activity with Microsoft's app center so I can track program crashes and fix them.

Line spacing?

**Comment by ronzie** [comment]
Good to know about the traffic.

The lines of text are closer together than I prefer. This started after v2.6.2. I will try to attach screenshots to demonstrate. I have the font size set to 18, the maximum.
![Tweetz 2 6 1](https://user-images.githubusercontent.com/7864635/89132684-ed2c7580-d4e3-11ea-8ec1-3fcc666fba0c.png)
![Tweetz 2 7 1](https://user-images.githubusercontent.com/7864635/89132693-f61d4700-d4e3-11ea-9d1c-c553a04d4f3c.png)

**Comment by mike-ward** [comment]
Yeah, that looks bad. The old one looks like it's too much though. Maybe something in between?

**Comment by mike-ward** [comment]
Here's an interim build with a fix.

https://github.com/mike-ward/tweetz/suites/999022801/artifacts/12906401

**Comment by ronzie** [comment]
Thanks, that's much better!
