### ISSUE TITLE
strange minimize

### ISSUE THREAD

**Issue by f242** [mike-ward/tweetz#41]
is this normal? why not to taskbar or tray?
![image](https://user-images.githubusercontent.com/10371194/91087168-b667fc00-e658-11ea-923c-8bb819198098.png)
tweetz 2.8.0
win 10 x64 2004

**Comment by mike-ward** [comment]
It's not normal and no one has reported it before. Probably some video driver issue if I had to guess.

**Comment by f242** [comment]
i see same behaviour in windows sandbox, just copied folder with program and run there in clear system

**Comment by mike-ward** [comment]
Do you see it on other systems?

**Comment by f242** [comment]
yes, tested on second PC but with same OS version

**Comment by mike-ward** [comment]
And did it happen in version 1909? It would have been helpful to let me know that version 2004 is a recent update.

**Comment by f242** [comment]
i can't test it, all my computers are have 2004

**Comment by mike-ward** [comment]
And Windows update won't offer to let me upgrade to 2004. Very strange.

**Comment by Wynolia** [comment]
Have this problem for a long time too (but too lazy to report it :( )
Actually on Win10 x64 1903 / Tweetz 2.7.1 (with tweetz-setup.exe) / Nvidia drivers 441.12
I think I already upgrade a version of Windows and my NVidia drivers since the problem appear

**Comment by mike-ward** [comment]
I did manage to get 2004 installed. Had to do a clean install. Still not seeing it. Are these 4K screens?

**Comment by f242** [comment]
did a clean installation yesterday, bug with minimize still present
i think you don't see it because you install some additional components for development

**Comment by f242** [comment]
little addition
when option "show is system tray" is turned off all works fine and normal minimized to task bar

**Comment by Wynolia** [comment]
I confirm that if "show in system tray" is checked, the bug is here.
But if I uncheck, it is working fine.
Tried this on Win10 x64 21H1 / Tweetz 2021.3

**Comment by mike-ward** [comment]
Implemented fix. Available in next release. In the meantime, you can use the non-production build at: https://github.com/mike-ward/tweetz/suites/3787528466/artifacts/93370280
