### ISSUE TITLE
Top bar and like/retweet icons missing

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [mike-ward/tweetz#45]
Basically the title. Running Windows 7 and the latest version of Tweetz.

![Screenshot of the client](https://user-images.githubusercontent.com/46287209/91640690-0e9a5780-e9e5-11ea-9424-76a69309ff51.jpg)

**Comment by mike-ward** [comment]
I'm surprised it works at all on Windows 7. The program is designed to work on Windows 10.
