### ISSUE TITLE
crash when i scroll down

### ISSUE THREAD

**Issue by f242** [mike-ward/tweetz#47]
program crashes witout any notification when i scroll down
v 2.8.3

**Comment by mike-ward** [comment]
From the stack trace it appears to be an internal WPF error. I'm puzzled why you have issues that no one else is reporting.

**Comment by mike-ward** [comment]
Looked at the stack trace again and found something I hadn't noticed before. 2.8.4 should address the issue.

**Comment by f242** [comment]
> I'm puzzled why you have issues that no one else is reporting.

i think people are lazy and not all have github account) 

thx for fix
