### ISSUE TITLE
Error: The Remote Server Returned an Error (429) Too Many Requests

### ISSUE THREAD

**Issue by darkufo** [mike-ward/tweetz#48]
![tweetz core_2020-09-19_16-34-56](https://user-images.githubusercontent.com/12990410/93670855-6123dc80-fa96-11ea-95ed-4af60ee54ee6.png)
I get this message a lot during the day. 

Is this something with Tweetz or are we running into a API Limit?

Screenshot attached.

**Comment by mike-ward** [comment]
That's normal. Twitter throttles requests to 15 requests per 15 minute window. Tweetz tries to stay within that limit but sometimes exceeds it. It will go away once the 15 minute window resets.
