### ISSUE TITLE
request: Smooth Scrolling

### ISSUE THREAD

**Issue by Viqsi** [mike-ward/tweetz#51]
Tweetz's scrolling right now is extremely jerky in behavior - it seems to scroll in 150-pixel "chunks" at a time rather than scrolling pixel-by-pixel like most things do nowadays (either that or they go line-by-line, but there really aren't consistent "lines" to work with here). Is this something that can be implemented?

(I've literally never done anything with C#, or I'd look into it...)

**Comment by mike-ward** [comment]
If you're talking about mouse wheel scrolling, Tweetz scrolls by the mouse wheel delta value which is system dependent. (See [WheelSpeedScrollViewer.cs](https://github.com/mike-ward/tweetz/blob/master/src/tweetz.core/Views/WheelSpeedScrollViewer.cs))

When I first implemented Tweetz it used 1 pixel per mouse wheel scroll but it didn't scroll nearly enough to be useful.

Many applications actually scroll by a number of lines and animate the transition. I think this is what you're requesting. 

WPF does not support this out of the box and it's a bit complicated to implement. To get an idea see https://stackoverflow.com/questions/20731402/animated-smooth-scrolling-on-scrollviewer.

I like the idea and will look into implementing it in a future version. Thanks for the feedback.

**Comment by mike-ward** [comment]
I have a prototype. Care to try it?

**Comment by mike-ward** [comment]
released in v2.8.5
