### ISSUE TITLE
tweetz 2.x regularly becomes unresponsive

### ISSUE THREAD

**Issue by Clorf** [mike-ward/tweetz#6]
Ever since the 2.0 update tweetz has been exhibiting an issue where if I leave it unattended for a minute or so, it becomes unresponsive.  

The window becomes smaller and gets a white line through it, scrolling doesn't work and the buttons don't respond.  A little while later I can click anywhere in the window and it'll go entirely white, but the standard Windows "This program is not responding" dialog will appear.  Selecting "Try to restore the app" actually works, but after that it's only a matter of minutes before it happens again.

**Comment by mike-ward** [comment]
That's really strange. 

Have any screen shots? 
Also, what version of Windows? 
Did you install it with the installer or use the zip archives and if so which one?
Does it happen on other computers?
Anything unusual about your computer?

Reproducing this is going to be key to fixing it.

Thanks for the bug report 👍

**Comment by Clorf** [comment]
It's funny, now that I have reason to catch it in the act, it's not happening anymore.

-Win10 x64
-Installer
-Don't have any other computers to test it on unfortunately
-It's a mid-high end gaming PC, so I think it's not likely to be a memory or CPU usage issue

The only thing that changed between yesterday and today is that my ISP just resolved an issue that was causing my area to have very slow and unreliable internet.   Is it possible that you're performing some network operation that you expect to be resolved quickly and the program chokes if that doesn't happen?

**Comment by mike-ward** [comment]
Not that I know of. I try to use async/await calls everywhere so the UI stays responsive. The resizing constantly issue feels like some third party app that remembers and positions desktop windows misbehaving. The only time Tweetz sets the window size/position is at startup. Anyways, glad it's working.

**Comment by Clorf** [comment]
I definitely don't have any apps like that running.  When I say the window becomes smaller, it's really just a very small vertical strip on the right side (where the scrollbar is) that disappears temporarily, not the actual window size changing.  It's a shame I didn't think to screenshot it when it was happening.

I'll be sure to capture it if it happens again.

**Comment by mike-ward** [comment]
Closing the issue for now. If it happens and you can catch it, we'll pick it back up.

**Comment by Clorf** [comment]
I finally managed to catch it in the act!  It happened when I clicked on a link to one of the tweets in my timeline.

![tweetz1cropped](https://user-images.githubusercontent.com/23464770/80291436-67d63f80-8702-11ea-9495-d439e7953b40.png)
![tweetz1scroll](https://user-images.githubusercontent.com/23464770/80291438-6a389980-8702-11ea-9b1b-be39f0c3f405.png)
![tweetz2cropped](https://user-images.githubusercontent.com/23464770/80291439-6c025d00-8702-11ea-85fc-4846c3b09d33.png)
