### ISSUE TITLE
Add Google Translate

### ISSUE THREAD

**Issue by Fruggy** [mike-ward/tweetz#61]

**Comment by mike-ward** [comment]
How do you envision the UI for this?

**Comment by Fruggy** [comment]
I would guess if the language isn't showing the preferred one then a button would be there to translate it to the preferred language.

I'm not good at this stuff and when I brought it up to you in email you asked me to put it here so I did.

**Comment by mike-ward** [comment]
I'll mimic what twitter does in their UI. It's sensible and doesn't involve popups.

**Comment by mike-ward** [comment]
Anyone interested in trying my first attempt at this? https://github.com/mike-ward/tweetz/suites/1609622510/artifacts/29447486

**Comment by Fruggy** [comment]
Works great Mike! Thanks!

**Comment by mike-ward** [comment]
This one is close to final. Also adds translate to quoted and related content when appropriate.

https://github.com/mike-ward/tweetz/suites/1612589201/artifacts/29536334

**Comment by Fruggy** [comment]
Thanks

**Comment by mike-ward** [comment]
OK, one small problem with the translation feature. It's not free. Currently, I'm using Microsoft's service because its free tier is the most generous (2M chars per month). I suspect that number will be exceeded at some point. The only sensible work around is to add some settings to allow folks to get their own service key from Microsoft. It's free but you do have to give them a credit card.  Thoughts?

**Comment by Fruggy** [comment]
If you have to add it, it's fine.
I'm wondering why Google Translate and Microsoft are not free to use and are they the same?

**Comment by mike-ward** [comment]
Both API's are free to use to a point. 

Google starts charging $15 per 1 million characters after the first 500,000 characters.

Microsoft starts charging $10 per 1 million characters after the first 2M characters.

**Comment by Fruggy** [comment]
![019](https://user-images.githubusercontent.com/20511428/103471294-7c1c1300-4d4c-11eb-8a61-04a09bdeed42.jpg)


Does this mean the free limit has been reached? 
I've been getting it for a few days now.
I also see nowhere to put the API from Google or Microsoft.

**Comment by mike-ward** [comment]
Could not get Microsoft to put a spending cap on my credit card for this service. They are not forthcoming about this and after a few calls had to cancel.

Google's API is damn near impossible to use and again, I don't see a way to limit spending. 

Other providers require a minimum of $25 per month and again, credit cards.

Usage was less than 10,000 chars per day. Well below limits but again, without a spending cap, not worth the risk.

I've got another solution in the works but it only supports 7 languages (en, ar, fr, de, it, pt, ru).  Should have something later today.

As to adding your own keys to an API, that's more complicated than it seems. In the case of the Microsoft API you need 3 other pieces of info by sides the API key. Not something I want to try and support.

**Comment by mike-ward** [comment]
fixed in v2.9.1
