### ISSUE TITLE
Menu takes up 2 rows since 2.9.1

### ISSUE THREAD

**Issue by ronzie** [mike-ward/tweetz#64]
Since upgrading Tweetz to v2.9.1 the menu at the top now takes up 2 rows instead of 1, as it did previously. 2.9.2 does the same. The Tweetz window width is set to 303. Screen shot attached.
![2021-01-05Tweetz2 9 2](https://user-images.githubusercontent.com/7864635/103700757-eadab580-4f72-11eb-936a-053e18ec4a57.png)

**Comment by mike-ward** [comment]
Odd indeed but I'm not seeing it here. No idea what it could be.

**Comment by mike-ward** [comment]
Well after playing around with it for a bit I found that it happens when the width ends in a 3, sometimes. Probably some rounding error in the width calculation. For now I suggest you set the width to 302 or 304.

**Comment by ronzie** [comment]
Thanks, 302 did the trick.

**Comment by mike-ward** [comment]
fixed in 2.9.3
