### ISSUE TITLE
Make the new look optional

### ISSUE THREAD

**Issue by sarcinelli86** [mike-ward/tweetz#67]
It would be nice to have the option to change the links, hashtags and mentions back to blue.

**Comment by mike-ward** [comment]
For some reason, blue is hard for me to pickup on slate background. Eyes are getting old I guess. I thought going to a contrast difference would be better. The gold-ish color is working better for me.  Does that work for you?

**Comment by sarcinelli86** [comment]
Yes, it's better now.
Thanks!
