### ISSUE TITLE
Allow a different media player to be used

### ISSUE THREAD

**Issue by RealTheSunCat** [mike-ward/tweetz#68]
I just downloaded Tweetz, and I love how it looks and feels. Definitely would want to use it over the web Twitter client.

However, when I try to play a video in the app, I get the following message:
![image](https://user-images.githubusercontent.com/44881120/105643051-df055380-5e8d-11eb-996f-78e9be313cf5.png)
My install of Windows doesn't appear to have Windows Media Player installed.
Is it possible to use an open source media player like VLC or mpv instead?

**Comment by mike-ward** [comment]
It's usually there. Do a search on the Internet on how to do install it.
