### ISSUE TITLE
Shortened Links Destination

### ISSUE THREAD

**Issue by sarcinelli86** [mike-ward/tweetz#7]
I miss this feature (showing the full link on mouseover) from the old client, is it possible to add it to the 2.0 version?

![mouse_over_1](https://user-images.githubusercontent.com/34447967/75405575-d78ba200-58ec-11ea-8c33-37afbdc1a8e8.png)

![mouse_over_2](https://user-images.githubusercontent.com/34447967/75405576-d8bccf00-58ec-11ea-9a70-b00dbfacf7e5.png)

**Comment by mike-ward** [comment]
Fixed and released in v2.1.0

**Comment by sarcinelli86** [comment]
Links from Google Shortener are not showing the full URL.

![2021-01-13 000517](https://user-images.githubusercontent.com/34447967/104401904-e5add580-5533-11eb-9fc8-8fa2a149510f.png)

**Comment by mike-ward** [comment]
I've seen this on occasion.  Sometimes the link takes too long (2 seconds) to resolve and timeouts. I'll bump it to 4 or 5 seconds in the next release.
