### ISSUE TITLE
Can Tweet font be changed?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [mike-ward/tweetz#89]
I know that its possible to change the font size used to render tweets, but is it possible to change the actual font itself, e.g. from Segoe UI to Tahoma?

**Comment by mike-ward** [comment]
First time anyone has ever asked. Not at this time.

**Comment by mike-ward** [comment]
Here's a non-production build that will allow you to change the font - https://github.com/mike-ward/tweetz/suites/3563859229/artifacts/85539257

1. Go to settings
2. Click the "Open Settings..." button. Notepad should display the settings file. 
3. Close Tweetz (important!)
4. Ediit the `FontFamily` setting in Notepad to the desired font
5. Save the file
6. Open Tweetz and verify font change
7. Revel in the glory that is Tweez (optional)

**Comment by mfreeman-xtivia** [comment]
Thank you Mike. Much appreciated
