### ISSUE TITLE
Image viewer shows gray box instead of image from tweet

### ISSUE THREAD

**Issue by ronzie** [mike-ward/tweetz#90]
Sometimes when I click on an image in Tweetz the viewer box that pops up shows a gray box instead of the image from the tweet. Screenshot attached. Using Tweetz v2021.3
![2021-09-19_Image_viewer_gray_box](https://user-images.githubusercontent.com/7864635/133939540-1291130b-c7a3-4b0e-af4c-a3e093df4400.png)

**Comment by mike-ward** [comment]
Um... Next time it happens tweet me a link to the problem tweet.

**Comment by mike-ward** [comment]
see if this build helps: https://github.com/mike-ward/tweetz/suites/3812209739/artifacts/94232719

**Comment by ronzie** [comment]
> 
> 
> Um... Next time it happens tweet me a link to the problem tweet.

This is the url of the tweet from the screenshot I posted. https://twitter.com/4TerryFarrell/status/1439662381555073030

I installed the new build and the problem hasn't happened yet.

**Comment by lgretton** [comment]
I've been seeing the same problem, and also approximately half the images in tweets in the main window not rendering (replaced with a static hourglass icon).

The new build seems to have fixed the problem for me too.

**Comment by mike-ward** [comment]
Closing. Fix will be available in the next release.
